### ISSUE TITLE
Rewire Machnine

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#11]
## Description

Rewire the internals of the machine to provide a cleaner look and simplify further modifcation of the machine.

## Related User Stories

- [Cleaning](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29365987)

## ToDo

- [x] 3D-Print Cable Holders for the ALU profiles
- [x] 3D-Print Holders for the PCB
- [x] Add proper connectors to the wires
- [x] [soldering PCB boards](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=30442907)
- [x] Reconnect systems
