### ISSUE TITLE
Replace Food Safety Sensitive 3D printed Parts

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#12]
## Description

Due to the fact that the current parts are not food safety and beverages from the machine can not be consumed, it is necessary to replace all components with direct contact to the beverages.

## Related User Stories

- [60 seconds to Drink](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367077)

## ToDo

- [x] Order food safe filament
- [x] test how food safe the material is by checking for water changes after laying the plastic in water.
- [x] Print **one** Leverage for Dispenser
- [x] Test leverage for breaking points
