### ISSUE TITLE
Prepare Hardware for Test with new Python Code

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#21]
## Description

Prepare Hardware in such a way, that the Display, Pi, Scale and Left Side is working

## ToDo

- [x] Make Pi Bootable
- [x] Display connected
- [x] Connect Scale to Pi
- [x] Complete rewiring left side
