### ISSUE TITLE
Preperation to present a demo on 11.07.23

### ISSUE THREAD

**Issue by asljhdgf** [ES-EDU-SIEGMA/Embedded-Controller#25]
#### The  goal is to present  a demo on 11.07.23.
- the machine should be able to dispense a drink.
- all hoppers should work.
- a drink should take less than 60 seconds.

group [meeting](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=32719282) on 07.07.23 10:00

## Related User Stories
- [get the machine to run](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=32421126)
- the main focus is to get the machine to dispense drinks.
- [60 Seconds to drink](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367077)
- secondary priority is to get the time it takes for a drink to be dispensed below 60 seconds

## Tasks this week
- [x] connect the hardware provisionally
- [x] test if all tinys work on the machine correctly
- [x] test if the machine can dispense a drink
- [x] measure the drink dispense timings.
- [x] check if the scale works correctly
- [x] test if the machine is in a demo ready state
