### ISSUE TITLE
Mount Display in front panel

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#26]
## Description

Install the newly delivered parts into the machine. This includes making an improved version of the display fixation in the front cover.

## Related User Stories

- [Cleaning](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29365987)
- [60 Seconds to drink](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367077)
- [Improve UI](https://github.com/orgs/ES-EDU-SIEGMA/projects/1/views/1?pane=issue&itemId=29367221)

## ToDo

- [x] Build display mount brackets
- [ ] Add Perspex cover over display-controller and PI
- [x] Install Components into Front Cover of the machine

**Comment by DavidFederl** [comment]
Required extra tools:
- [Gewindeeinsatz](https://www.amazon.de/Turmberg3D-L%C3%B6tkolben-Einschmelzhilfe-Gewindeeins%C3%A4tze-Einschmelzmuttern/dp/B09NYLSKPY/ref=bmx_dp_o3cuoi2o_sccl_3_2/260-5208990-7250312?pd_rd_w=EnBzS&content-id=amzn1.sym.f659f91d-d97b-4ad7-8b13-dcf97e84ea29&pf_rd_p=f659f91d-d97b-4ad7-8b13-dcf97e84ea29&pf_rd_r=KKBZG3B5E97EEWQV97ER&pd_rd_wg=KOqsL&pd_rd_r=85ee05ca-a0b5-4649-8e13-10f76911afc1&pd_rd_i=B097RR1KCB&th=1)
- [Einschmelzhilfe](https://www.amazon.de/Turmberg3D-L%C3%B6tkolben-Einschmelzhilfe-Gewindeeins%C3%A4tze-Einschmelzmuttern/dp/B097RR1KCB/ref=bmx_dp_o3cuoi2o_sccl_3_2/260-5208990-7250312?pd_rd_w=EnBzS&content-id=amzn1.sym.f659f91d-d97b-4ad7-8b13-dcf97e84ea29&pf_rd_p=f659f91d-d97b-4ad7-8b13-dcf97e84ea29&pf_rd_r=KKBZG3B5E97EEWQV97ER&pd_rd_wg=KOqsL&pd_rd_r=85ee05ca-a0b5-4649-8e13-10f76911afc1&pd_rd_i=B097RR1KCB&th=1)
- [M3 Schraubensortiment](https://www.amazon.de/joyan-Schrauben-Innensechskant-Innensechskantschrauben-Linsenkopfschrauben/dp/B09NDPH4RN/ref=sr_1_5?crid=XX9RH83KI7G4&keywords=m3+schrauben+flachkopf&qid=1700820589&sprefix=M3+Schrauben+%2Caps%2C114&sr=8-5)

**Comment by DavidFederl** [comment]
Only need to add cutouts to perspex cover!
