### ISSUE TITLE
Test/Replace Motor/Controller

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#28]
## Description

The **first** motor on the right side doesn't work correctly. Check if it is broken and if so replace it!

## Related User Stories

- #71 
- #80 

## ToDo

- [x] Replace all Motor Controller (if broken)
- [x] Check if Motor is broken (replace if required)
- [x] Fix ropes (length needs to be adjusted)

**Comment by HuangQing23** [comment]
Using integrationTest-motor tested the Motors of right side. They can correctly set up, move up and down. The first motor on the right side also works correctly, so maybe we can keep it. 

We may need to adjust the lengths of the lines of Motor 0, 1, and 2. Only Motor 3 can turn up after going all the way down.

**Comment by DavidFederl** [comment]
The motor is okay. To my point of view the PCB connections were faulty.

**Comment by DavidFederl** [comment]
We should test the length of all ropes and adjust each of them accordingly

**Comment by HuangQing23** [comment]
Dispenser 1 is ok, dispenser 2 needs to add some weight to touch the limitswitch,the rope is ok. Dispenser 3 and 4 is ok.

**Comment by HuangQing23** [comment]
> Dispenser 1 is ok, dispenser 2 needs to add some weight to touch the limitswitch,the rope is ok. Dispenser 3 and 4 is ok.

copy from #85 
To make the motors work properly, we should get the rope wrapped clockwise around the motor's rotating shaft. This is because our function 'moveMotorDowm' will make the motor shaft rotates clockwise. If the rope is wrapped in the opposite direction of the motor shaft rotation due to rope length or over-rotation of the shaft, then the input command will rotate in the opposite direction of the actual rotation.

**Comment by HuangQing23** [comment]
For the lever, the distance between its root and the limitswitch when it is leveled is important for the smoothness of the system. Because motor4 triggers the limitswitch almost instantly when it descends, whereas the other ones only touch the limitswitch after a certain period of moveMotorDown.

**Comment by HuangQing23** [comment]
If we have problems with over-rotation or lagging while testing, we may need to cut the power to refresh the contents of the tiny. Otherwise the lever/motor may move abnormally (continuing from the last error state).
